### ISSUE TITLE
Compilation error on PowerPC

### ISSUE THREAD

**Issue by neheb** [facebook/fbzmq#13] opened 2019-06-19 17:33 UTC
```
[ 50%] Building CXX object CMakeFiles/fbzmq.dir/service/logging/LogSample.cpp.o
/builder/powerpc_8540/build/sdk/build_dir/target-powerpc_8540_musl/fbzmq-2019.06.10.00/fbzmq/async/ZmqTimeout.cpp: In static member function 'static std::unique_ptr<fbzmq::ZmqTimeout> fbzmq::ZmqTimeout::make(fbzmq::ZmqEventLoop*, fbzmq::TimeoutCallback)':
/builder/powerpc_8540/build/sdk/build_dir/target-powerpc_8540_musl/fbzmq-2019.06.10.00/fbzmq/async/ZmqTimeout.cpp:40:59: error: 'new' of type 'fbzmq::{anonymous}::ZmqTimeoutWrapper' with extended alignment 16 [-Werror=aligned-new=]
       new ZmqTimeoutWrapper(eventLoop, std::move(callback)));
                                                           ^
/builder/powerpc_8540/build/sdk/build_dir/target-powerpc_8540_musl/fbzmq-2019.06.10.00/fbzmq/async/ZmqTimeout.cpp:40:59: note: uses 'void* operator new(std::size_t)', which does not have an alignment parameter
/builder/powerpc_8540/build/sdk/build_dir/target-powerpc_8540_musl/fbzmq-2019.06.10.00/fbzmq/async/ZmqTimeout.cpp:40:59: note: use '-faligned-new' to enable C++17 over-aligned new support
```

I'm guessing this is a C++17 feature being used.

https://downloads.openwrt.org/snapshots/faillogs/powerpc_8540/packages/fbzmq/compile.txt

**Comment by saifhhasan** [comment] 2019-06-27 19:10
Hi @neheb - Since you're working on it and have a way to reproduce it, we will appreciate the pull request.

**Comment by neheb** [comment] 2019-06-27 19:35
There are two solutions. Either change the standard to C++17 or pass -faligned-new to CXXFLAGS. Which is preferred?

**Comment by saifhhasan** [comment] 2019-06-27 20:42
You make a good suggestion. `-faligned-new` to `CMAKE_CXX_FLAGS` to your build script will be best. Closing as it will not need any changes in fbzmq. 

```
CMAKE_CXX_FLAGS=-faligned-new cmake fbzmq/
make
```

**Closed by saifhhasan** 2019-06-27 20:42 UTC
